# docker-compose.yml
version: '2'

services:
  server:
    build: ./bookmarks_server/
    ports:
      - "5001:5000"
      - "8081:8080"
    depends_on:
      - "database"
    volumes:
      - ./bookmarks_server:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE=mongodb://database:27017/
# mongodb://host.docker.internal:27018/
  database:
    image: mongo:latest
    volumes:
      - ./bookmarks_database/data/db:/data/db
    ports:
      - 27018:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    depends_on:
      - "database"
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://database:27017/
  frontend:
    build: ./bookmarks_frontend/
    ports:
      - "3001:3000"
    volumes:
      - ./bookmarks_frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    # In order to get CORS enabled
      - NODE_ENV=development
    # For react application to see an environment variable it must be prefixed with "REACT_APP_"
    # Todo: use nginx to access container's endpoint. For now hardcoding host ip address and port
      - REACT_APP_BACKEND_URL=http://${IP}:8081
      #- REACT_APP_BACKEND_URL=http://192.168.1.38:8081
# http://host.docker.internal:8081/
# - REACT_APP_BACKEND_URL=http://server:8081/
# REACT_APP_BACKEND_URL=http://server:8080/